services:
  # PHP Application
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=capstone_user
      - DB_PASSWORD=capstone_password
      - DB_NAME=capstone_db
    networks:
      - capstone_network

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: capstone_db
      MYSQL_USER: capstone_user
      MYSQL_PASSWORD: capstone_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - capstone_network

  # phpMyAdmin (optional, for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: capstone_user
      PMA_PASSWORD: capstone_password
    depends_on:
      - db
    networks:
      - capstone_network

volumes:
  mysql_data:

networks:
  capstone_network:
    driver: bridge
